version: "3"

services:
  postgres:
    image: postgres:13-alpine3.16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: imageUI